/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package modul1.gradle;

import com.google.gson.Gson;

import java.util.LinkedHashMap;

public class MyName {
// java -cp myname.jar modul1.gradle.MyName
    public static void main(String[] args) {
        LinkedHashMap<String, String> name = new LinkedHashMap<>();
        name.put("name","Viktoriia");
        name.put("lastName","Verner");
        String json = new Gson().toJson(name);
        System.out.println("json = " + json);
    }
}
