/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package modul1.gradle;

import org.junit.Test;

public class MyNameTest {
    @Test public void appHasAGreeting() {
        MyName classUnderTest = new MyName();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
